resource_types:
- name: ansible-playbook
  type: docker-image
  source:
    repository: troykinsella/concourse-ansible-playbook-resource
    tag: latest

resources:
- name: ansible
  type: ansible-playbook
  source:
    debug: false
    #user: ubuntu
    #ssh_private_key: ((ansible_ssh_private_key))
    #vault_password: ((ansible_vault_password))
    #verbose: v

- name: master
  type: git
  source:
    uri: https://github.com/shimpeiN/portfolio.git
    branch: main
    username: shimpeiN
    password: Xshinpei428


jobs:
- name: provision-frontend
  plan:
  - get: master # git resource
  - put: ansible
    params:
      check: true
      diff: true
      inventory: inventory/site_test.yml
      playbook: site_test.yml
      path: master/ansible                           
