jobs:
  - name: job-sample
    plan:
      - task: task-sample
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: 3.5
          run: 
            path: /bin/sh
            args:
              - -c
              - -x
              - |
                date
